language: python
python: "3.5"
install:
  # Upgrade pip and wheel to get proper wheel caching
  - pip install --upgrade pip==8.1.1 wheel==0.29.0

  # Instal and build project
  - pip install -r requirements.txt
  - pip install -e .
  - pip install python-coveralls
  - mkdir -p var/www/static var/www/media
  - bin/initsettings

  # Install test dependencies
  - yarn global add eslint@2.11.1
script:
  - py.test -vvra --tb=native --flake8 --doctest-modules --cov manopozicija --cov-report term-missing manopozicija
after_success:
  - coveralls
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/buildout
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
    - mkdir -p $HOME/.cache/buildout/eggs $HOME/.cache/buildout/downloads
